import {
  FaHtml5,
  FaCss3Alt,
  FaJsSquare,
  FaReact,
  FaBootstrap,
  FaGitAlt,
  FaGithub,
  FaFigma,
  FaCheckCircle,
} from 'react-icons/fa';

import {
  SiRedux,
  SiTailwindcss,
  SiAntdesign,
  SiFirebase,
  SiNetlify,
  SiVercel,
  SiReactrouter,
  SiFormik,
  SiVorondesign,
} from 'react-icons/si';

import { MdAccessTime, MdViewCarousel } from 'react-icons/md';

//
export const skills = [
  {
    name: 'HTML5',
    icon: <FaHtml5 />,
    color: '#e44d26',
    level: 95,
  },
  {
    name: 'CSS3',
    icon: <FaCss3Alt />,
    color: '#264de4',
    level: 90,
  },
  {
    name: 'Day.js',
    icon: <MdAccessTime />,
    color: '#2d8cf0',
    level: 90,
  },
  {
    name: 'Swiper.js',
    icon: <MdViewCarousel />,
    color: '#00aaff',
    level: 90,
  },

  {
    name: 'JavaScript',
    icon: <FaJsSquare />,
    color: '#f0db4f',
    level: 90,
  },
  {
    name: 'JavaScript (ES6+)',
    icon: <FaJsSquare />,
    color: '#f0db4f',
    level: 88,
  },
  {
    name: 'React.js',
    icon: <FaReact />,
    color: '#61dafb',
    level: 88,
  },
  {
    name: 'Redux',
    icon: <SiRedux />,
    color: '#764abc',
    level: 85,
  },
  {
    name: 'Redux Toolkit',
    icon: <SiRedux />,
    color: '#764abc',
    level: 80,
  },
  {
    name: 'Tailwind CSS',
    icon: <SiTailwindcss />,
    color: '#38bdf8',
    level: 92,
  },
  {
    name: 'Bootstrap',
    icon: <FaBootstrap />,
    color: '#563d7c',
    level: 80,
  },
  {
    name: 'Ant Design',
    icon: <SiAntdesign />,
    color: '#fa541c',
    level: 75,
  },
  {
    name: 'shadcn/ui',
    icon: <SiVorondesign />,
    color: '#fa541c',
    level: 75,
  },
  {
    name: 'DOM Manipulation',
    icon: <FaJsSquare />,
    color: '#f0db4f',
    level: 80,
  },
  {
    name: 'Component Based Architecture',
    icon: <FaReact />,
    color: '#61dafb',
    level: 85,
  },
  {
    name: 'Formik',
    icon: <SiFormik />,
    color: '#635bff',
    level: 78,
  },
  {
    name: 'Yup',
    icon: <FaCheckCircle />,
    color: '#34d399',
    level: 75,
  },
  {
    name: 'React Router',
    icon: <SiReactrouter />,
    color: '#ca4245',
    level: 85,
  },
  {
    name: 'React Icons',
    icon: <FaReact />,
    color: '#61dafb',
    level: 70,
  },
  {
    name: 'React Toastify',
    icon: <FaCheckCircle />,
    color: '#34d399',
    level: 70,
  },
  {
    name: 'Git',
    icon: <FaGitAlt />,
    color: '#f1502f',
    level: 85,
  },
  {
    name: 'GitHub',
    icon: <FaGithub />,
    color: '#333',
    level: 90,
  },
  {
    name: 'VS Code',
    icon: <FaGithub />,
    color: '#0078d7',
    level: 90,
  },
  {
    name: 'Vercel',
    icon: <SiVercel />,
    color: '#000',
    level: 80,
  },
  {
    name: 'Netlify',
    icon: <SiNetlify />,
    color: '#00c7b7',
    level: 85,
  },
  {
    name: 'Figma',
    icon: <FaFigma />,
    color: '#a259ff',
    level: 75,
  },
  {
    name: 'Firebase',
    icon: <SiFirebase />,
    color: '#ffa611',
    level: 80,
  },
  {
    name: 'Responsive Web Design',
    icon: <FaCheckCircle />,
    color: '#22c55e',
    level: 95,
  },
  {
    name: 'Component Reusability',
    icon: <FaCheckCircle />,
    color: '#22c55e',
    level: 90,
  },
  {
    name: 'Mobile First Design',
    icon: <FaCheckCircle />,
    color: '#22c55e',
    level: 88,
  },
  {
    name: 'Basic Firebase Auth',
    icon: <SiFirebase />,
    color: '#ffa611',
    level: 78,
  },
  {
    name: 'JSON Data Handling',
    icon: <FaCheckCircle />,
    color: '#22c55e',
    level: 80,
  },
  {
    name: 'Context API',
    icon: <FaReact />,
    color: '#61dafb',
    level: 75,
  },
  {
    name: 'State Management',
    icon: <SiRedux />,
    color: '#764abc',
    level: 80,
  },
  {
    name: 'Modal System',
    icon: <FaCheckCircle />,
    color: '#22c55e',
    level: 75,
  },
  {
    name: 'Form Validation',
    icon: <FaCheckCircle />,
    color: '#22c55e',
    level: 80,
  },
];
